#import "/lib.typ": *

== Elliptic Functions

The theory of elliptic functions is an elaborate chapter of complex analysis, with origins in seemingly trivial problems of calculus. In the 18th century, mathematicians studying the rectification (arc length calculation) of curves such as the ellipse and the lemniscate discovered that these could not be expressed in terms of elementary functions, leading to the introduction of elliptic integrals. Inverting these integrals gave rise to elliptic functions, which extend the idea of trigonometric functions by being _doubly periodic_ in the complex plane. Closely related ideas also appeared in conformal mapping, such as the Schwarz--Christoffel transformation (@sec:schwarzchristoffeltransformation) between the upper half-plane and rectangles. Henceforth, elliptic functions became a central subject related to calculus, geometry, and complex analysis.

It is well-known in real analysis that a periodic function can be expressed as a Fourier series, with terms as the trivial functions $sin, cos, dots, sin(n x), cos(n x)$. Such functions are called _singly periodic_.

If $f : CC -> extcomplex$ is meromorphic with period $omega in CC^*$, then it has the Fourier expansion
$
  f(z) = sum_(n=-oo)^oo c_n exp((2 uppi ii n z) / omega), quad c_n = 1 / omega integral_a^(a + omega) f(z) exp(-(2 uppi ii n z) / omega) dz quad forall n in ZZ.
$
We briefly justify this as follows.
$f$ being periodic with period $omega$ implies that by letting $w = exp((2 uppi ii z) / omega)$, the function $g(w) = f(omega / (2 uppi ii) log w) = f(z)$ is well-defined and single-valued on $extcomplex without {0}$ (except for at finitely many isolated poles). Hence, $g$ admits a Laurent expansion
$
  g(w) = sum_(n=-oo)^oo c_n w^n, quad c_n = 1 / (2 uppi ii) integral.cont_(abs(w) = r) g(w) w^(-n - 1) dif w quad forall n in ZZ,
$
for $r > 0$. Substituting back $w = exp((2 uppi ii z) / omega)$, $dif w = (2 uppi ii) / omega exp((2 uppi ii z) / omega) dz$ gives the desired Fourier expansion of $f$:
$
  c_n & = 1 / (2 uppi ii) integral_(omega / (2 uppi ii) log(r))^(omega / (2 uppi ii) (log(r) + 2 uppi ii)) f(z) exp(-(2 uppi ii n z) / omega) exp(-(2 uppi ii z) / omega) (2 uppi ii) / omega exp((2 uppi ii z) / omega) dz \
  & = 1 / omega integral_(omega / (2 uppi ii) log(r))^(omega / (2 uppi ii) log(r) + omega) f(z) exp(-(2 uppi ii n z) / omega) dz.
$
The term `"elliptic function"` itself refers to a _doubly periodic_ meromorphic function. More precisely, a meromorphic function $f : CC -> extcomplex$ is called an _elliptic function_ if there exist two $CC$-linearly independent periods $omega_1, omega_2 in CC^*$ such that $f(z + omega_1) = f(z + omega_2) = f(z)$ for all $z in CC$. Without loss of generalization, we will assume that $Im(omega_2 / omega_1) > 0$ (linear independence guarantees that this is non-vanishing, while we may consider periods $omega_1, -omega_2$ or $-omega_1, omega_2$ to achieve the same result). Any period of $f$ is in the form of
$
  omega = m omega_1 + n omega_2 quad m, n in ZZ.
$
The set of all periods of $f$ forms a _period lattice_
$
  Lambda = Lambda(omega_1, omega_2) = omega_1 ZZ + omega_2 ZZ = {m omega_1 + n omega_2 : m, n in ZZ}.
$
The set formed by $Lambda$ is a discrete additive (any sum of two points in the lattice remain in the lattice) subgroup of $CC$, a free $ZZ$-module of rank $2$ (generated by the basis ${omega_1, omega_2}$).

For any point $alpha in CC$, the complex parallelogram generated by
$
  P = {alpha + t_1 omega_1 + t_2 omega_2 : t_1, t_2 in [0, 1)},
$
is known as a _fundamental parallelogram of_ $Lambda$.

#figure(
  box(
    inset: 1em,
    stroke: 0.6pt,
    radius: 4pt,
    width: 100%,
    [Illustration placeholder for the deformation of a homeomorphism between a rectangle with opposite sides _identified_ and a torus. Raw TikZ source is preserved below for manual conversion.],
  ),
  caption: [Illustration of the deformation of a homeomorphism between a rectangle with opposite sides _identified_ and a torus.],
) <fig:identifiedrectagletotorushomeomorphism>

/*
\begin{figure}
    \centering
    \begin{tikzpicture}
        \begin{scope}
            \draw[thick] (0,0) rectangle (1.5,1.2);
            \draw[-{Stealth[length=1.5mm, width=1.5mm]},thick, dashed] (0.1,0.2)--(0.1,1.0);
            \draw[-{Stealth[length=1.5mm, width=1.5mm]},thick, dashed] (1.4,0.2)--(1.4,1.0);
            \draw[-{Stealth[length=1.5mm, width=1.5mm]},thick] (0.2,0.1)--(1.3,0.1);
            \draw[-{Stealth[length=1.5mm, width=1.5mm]},thick] (0.2,1.1) -- (1.3,1.1);
        \end{scope}
        \begin{scope}[xshift=2.7cm, yshift=0.6cm]
            \pgfmathsetmacro{\smallradius}{0.25}
            \pgfmathsetmacro{\largeradius}{0.3}
            \pgfmathsetmacro{\cylinderlength}{1.5}
            \pgfmathsetmacro{\arrowthreshold}{0.3}
            \draw[thick] (0,0) ellipse ({\smallradius} and {\largeradius});

            \draw[-{Stealth[length=1.5mm, width=1.5mm]}, thick, dashed] ({\smallradius*(1-\arrowthreshold)},0) arc (360:20:{\smallradius*(1-\arrowthreshold)} and {\largeradius*(1-\arrowthreshold)});
            \draw[-{Stealth[length=1.5mm, width=1.5mm]}, dashed] ({\smallradius*(1-\arrowthreshold)+\cylinderlength},0) arc (360:20:{\smallradius*(1-\arrowthreshold)} and {\largeradius*(1-\arrowthreshold)});

            \draw[thick] (0,-\largeradius) -- (\cylinderlength,-\largeradius);
            \draw[thick] (0,\largeradius) -- (\cylinderlength,\largeradius);
            \draw[thick] (\smallradius,0) -- (\smallradius + \cylinderlength,0);

            \draw (\cylinderlength,-\largeradius) arc (270:90:{\smallradius} and {\largeradius});
            \draw[thick] (\cylinderlength,\largeradius) arc (90:-90:{\smallradius} and {\largeradius});

            \draw[-{Stealth[length=1.5mm, width=1.5mm]}] (\smallradius+\arrowthreshold, 0)--(\cylinderlength+\smallradius-\arrowthreshold, 0);
        \end{scope}
        \begin{scope}[xshift=6.2cm, yshift=0.3cm]
            \pgfmathsetmacro{\smallradius}{0.25}
            \pgfmathsetmacro{\largeradius}{0.3}
            \pgfmathsetmacro{\halfcenterdistance}{0.65}
            \pgfmathsetmacro{\arrowthreshold}{0.3}

            \draw[thick] (-\halfcenterdistance,0) ellipse ({\largeradius} and {\smallradius});
            \draw[thick] (\halfcenterdistance,0) ellipse ({\largeradius} and {\smallradius});

            \draw[-{Stealth[length=1.5mm, width=1.5mm]}, thick, dashed] ({-\halfcenterdistance+\largeradius*(1-\arrowthreshold)},0) arc (360:20:{\largeradius*(1-\arrowthreshold)} and {\smallradius*(1-\arrowthreshold)});

            \draw[-{Stealth[length=1.5mm, width=1.5mm]}, thick, dashed] ({\halfcenterdistance-\largeradius*(1-\arrowthreshold)},0) arc (-180:160:{\largeradius*(1-\arrowthreshold)} and {\smallradius*(1-\arrowthreshold)});

            \draw[thick] (\halfcenterdistance-\largeradius,0) arc (0:180:{\halfcenterdistance-\largeradius} and {(\halfcenterdistance-\largeradius)*\smallradius/\largeradius});
            \draw[thick] (\halfcenterdistance+\largeradius,0) arc (0:180:{\halfcenterdistance+\largeradius} and {(\halfcenterdistance+\largeradius)*\smallradius/\largeradius});
        \end{scope}
        \begin{scope}[xshift=9cm, yshift=0.6cm]
            \pgfmathsetmacro{\smallradius}{0.25}
            \pgfmathsetmacro{\largeradius}{0.3}

            \draw[thick] (0,0) ellipse (1 and 0.7);
            \begin{scope}
                \clip (-0.6,0) rectangle (0.6,0.4);
                \draw[thick] (-0.5,-0.2) arc (180:0:{0.5} and {0.5*0.7});
            \end{scope}
            \begin{scope}
                \clip (-0.6,0.1) rectangle (0.6,-0.3);
                \draw[thick] (-0.5,0.2) arc (180:360:{0.5} and {0.5*0.7});
            \end{scope}
        \end{scope}
        \draw[-{Stealth[length=1.5mm, width=1.5mm]}, thick] (1.7,0.6) -- (2.3,0.6);
        \draw[-{Stealth[length=1.5mm, width=1.5mm]}, thick] (4.65,0.6) -- (5.1,0.6);
        \draw[-{Stealth[length=1.5mm, width=1.5mm]}, thick] (7.3,0.6) -- (7.8,0.6);
    \end{tikzpicture}
    \caption{Illustration of the deformation of a homeomorphism between a rectangle with opposite sides \emph{identified} and a torus.}\label{fig:identifiedrectagletotorushomeomorphism}
\end{figure}
*/

The properties of an elliptic function can be more easily observed on its fundamental parallelogram, since the values of $f$ on $CC$ are fully represented by its values on $P$. Because the opposite sides of the parallelogram are _identified_ (treated to be the same, or topologically `"glued together"`) by the periodicity of $f$, the fundamental parallelogram is homeomorphic to a torus, as visualized in @fig:identifiedrectagletotorushomeomorphism.

Let $CC$ be closed under addition and let $Lambda$ be the subgroup of $CC$. Then, the quotient group $CC \/ Lambda$ is compact as it is homeomorphic to a torus, which is endowed with a compact topology. Hence, Liouville (@thm:liouville) implies that if $f$ does not have poles, then it must be constant:

#theorem("Liouville")[
  Any elliptic function $f$ with period lattice $Lambda$ that is holomorphic on $CC$ is constant.
] <thm:liouvilleelliptic>

#proposition[
  The number of zeros and poles (counting multiplicities and orders) of a non-constant elliptic function $f$ in $CC \/ Lambda$ is finite, where $Lambda$ is the period lattice of $f$.
]

#proof[
  Let $P$ be a fundamental parallelogram of $Lambda$. It suffices to show that $f$ has finitely many zeros and poles in $overline(P)$. If there are infinitely many poles in $overline(P)$, then by the Bolzano--Weierstrass Theorem (@thm:bolzanoweierstrass), there exists an accumulation point $z_0 in overline(P)$ of poles. Hence, $z_0$ cannot be an isolated singularity, contradicting meromorphy (more succinctly, $z_0$ is then an essential singularity on the Riemann sphere).

  Under the assumption that $f equiv.not 0$, the same argument shows that $1 / f$ has finitely many poles in $overline(P)$, or equivalently, that $f$ has finitely many zeros in $overline(P)$.
]

#proposition[
  For any elliptic function $f$ with period lattice $Lambda$, the sum of the residues of $f$ in $CC \/ Lambda$ is zero.
] <prop:ellipticfunctionresiduesum>

#proof[
  Let $alpha$, $alpha + omega_1$, $alpha + omega_2$, and $alpha + omega_1 + omega_2$ be the vertices of a fundamental parallelogram $P$ of $Lambda$ such that $partial P$ does not pass through the poles $f$. By the Residue Theorem (@thm:residuethm), we have
  $
    2 uppi ii sum_(z_k in P) Res_(z = z_k) f(z) = integral.cont_(partial P) f(z) dz,
  $
  where the sum is over all poles $z_k$ of $f$ in $CC \/ Lambda$ (effectively $P$). The integral is equivalent to
  $
    integral.cont_(partial P) f(z) dz & = plus.minus (integral_alpha^(alpha + omega_1) + integral_(alpha + omega_1)^(alpha + omega_1 + omega_2) + integral_(alpha + omega_1 + omega_2)^(alpha + omega_2) + integral_(alpha + omega_2)^alpha) f(z) dz \
    & = plus.minus (integral_alpha^(alpha + omega_1) + integral_alpha^(alpha + omega_2) + integral_(alpha + omega_1)^alpha + integral_(alpha + omega_2)^alpha) f(z) dz = 0
  $
  by the periodicity of $f$.
]

#theorem[
  For any non-constant elliptic function $f$ with period lattice $Lambda$, the number of zeros and poles (counting multiplicities and orders, respectively) in $CC \/ Lambda$ are equal.
] <thm:ellipticfunctionnumberofzerosandpoles>

#proof[
  Let $P$ be a fundamental parallelogram of $Lambda$ such that $partial P$ $f$ has no poles or zeros thereon. By the Argument Principle (@thm:argumentprinciplemeromorphic), we have
  $
    1 / (2 uppi ii) integral.cont_(partial P) (f'(z)) / (f(z)) dz = " # of zeros in " P " - " " # of poles in " P
  $
  where the sums are over all zeros and poles of $f$ in $CC \/ Lambda$ (effectively $P$) counted with multiplicities and orders, respectively. By assumption, $f' equiv.not 0$, and hence $f' / f$ is non-constant and elliptic with period lattice $Lambda$. By @prop:ellipticfunctionresiduesum, the integral vanishes and hence the assertion follows.
]

#proposition[
  Suppose $f$ is a non-constant elliptic function with period lattice $Lambda$. Then $f$ attains every value in $extcomplex$ the same number of times (counting multiplicities) in $CC \/ Lambda$.
]

#proof[
  Assume that $z != oo$ and suppose $P$ is a fundamental parallelogram that does not pass through a pole. Then the number of times $zeta |-> f(zeta) - z$ attains $0$ and $oo$ in $CC \/ Lambda$ are equal by @thm:ellipticfunctionnumberofzerosandpoles. In other words, $f$ has the same number of poles as the number of times it attains any finite complex number.
]

Hence, it is only natural to quantify this number:

#definition[
  An elliptic function $f$ is said to be of _order_ $n$ iff it attains every value in $extcomplex$ exactly $n$ times (counting multiplicities) in $CC \/ Lambda$, where $Lambda$ is the period lattice of $f$ (in other words, the number of poles of $f$ in a fundamental parallelogram, counted according to order, is $n$).
]

#proposition[
  A non-constant elliptic function $f$ is of order $gt.eq 2$.
]

#proof[
  If $f$ is of order $1$, then $f$ has a simple pole at some $z_0$ in a fundamental parallelogram of its period lattice $Lambda$. By the simplicity of the pole, it must have a nonzero residue there. By @prop:ellipticfunctionresiduesum, this is an impossibility.
]

#theorem[
  Suppose that $f$ is a non-constant elliptic function with period lattice $Lambda$. Let $a_1, dots, a_n$ and $b_1, dots, b_n$ be the zeros and poles (counting multiplicities and orders, respectively) in a fundamental parallelogram $P$ (whose boundary intersects neither zeros or poles) of $Lambda$. Then
  $
    sum_(j=1)^n a_j - sum_(j=1)^n b_j in Lambda,
  $
  or in other words, this difference is also a period of $f$.
]

#proof[
  By @thm:generalizedargumentprinciple, the quantity in question is equal to
  $
    & sum_(j=1)^n a_j - sum_(j=1)^n b_j = 1 / (2 uppi ii) integral.cont_(partial P) (z f'(z)) / (f(z)) dz \
    &wide = plus.minus 1 / (2 uppi ii) (integral_alpha^(alpha + omega_1) + integral_(alpha + omega_1)^(alpha + omega_1 + omega_2) + integral_(alpha + omega_1 + omega_2)^(alpha + omega_2) + integral_(alpha + omega_2)^alpha) (z f'(z)) / (f(z)) dz \
    &wide = plus.minus 1 / (2 uppi ii) (integral_alpha^(alpha + omega_1) + integral_(alpha + omega_2)^alpha) (z f'(z)) / (f(z)) dz \
    & wide quad plus.minus 1 / (2 uppi ii) (integral_alpha^(alpha + omega_2) ((z + omega_1) f'(z)) / (f(z)) dz + integral_(alpha + omega_1)^alpha ((z + omega_2) f'(z)) / (f(z)) dz) \
    &wide = plus.minus 1 / (2 uppi ii) (integral_(alpha + omega_1)^alpha (omega_2 f'(z)) / (f(z)) dz + integral_alpha^(alpha + omega_2) (omega_1 f'(z)) / (f(z)) dz) \
    &wide = plus.minus (omega_2) / (2 uppi ii) (log f(alpha) - log f(alpha + omega_1)) plus.minus (omega_1) / (2 uppi ii) (log f(alpha + omega_2) - log f(alpha)) \
    &wide = plus.minus (omega_2) / (2 uppi ii) log(1) plus.minus (omega_1) / (2 uppi ii) log(1).
  $
  Since the branches of the multi-valued logarithm differ by integer multiples of $2 uppi ii$, the assertion follows.
]

#chapter-section("weierstrass_elliptic_functions")[
  #include "weierstrass_elliptic_functions/index.typ"
]
#chapter-section("jacobi")[
  #include "jacobi/index.typ"
]
#chapter-section("modular_group")[
  #include "modular_group/index.typ"
]
